#!/usr/bin/env node
/**
 * export-cookies.mjs — mint a Netscape cookies.txt from the Playwright profile.
 *
 * The Playwright profile is the single source of session truth: it is logged in
 * by construction, whereas your everyday browser may have no Douyin session at
 * all. yt-dlp cannot read a Playwright profile directly, but it accepts
 * `--cookies <netscape-file>`, so we export.
 *
 * Usage: node export-cookies.mjs [-o FILE] [--profile DIR]
 */
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { loadPlaywright, PROFILE_DIR, COOKIE_FILE } from './paths.mjs';

let output = COOKIE_FILE;
let profileDir = PROFILE_DIR;

const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === '-o' || argv[i] === '--output') output = argv[++i];
  else if (argv[i] === '--profile') profileDir = argv[++i];
  else {
    console.error(`error: unknown option '${argv[i]}'`);
    process.exit(2);
  }
}

const { chromium } = await loadPlaywright();
const context = await chromium.launchPersistentContext(profileDir, { headless: true });
try {
  // Anchored on a label boundary: `.douyin.com`, `douyin.com` and
  // `www.douyin.com` qualify, a lookalike ending in `…notdouyin.com` does not.
  const cookies = (await context.cookies()).filter((c) =>
    /(^|\.)douyin\.com$/.test(c.domain),
  );

  if (cookies.length === 0) {
    console.error(
      'error: no douyin.com cookies in the profile — the session is empty.\n' +
        '  Establish one with: node collect-douyin-ids.mjs --login <profile-url>',
    );
    process.exit(1);
  }

  // Netscape format: domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
  // Session cookies (expires === -1) get 0, which yt-dlp reads as non-expiring.
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by export-cookies.mjs — regenerated automatically when stale.',
    ...cookies.map((c) => {
      const includeSub = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const expiry = c.expires && c.expires > 0 ? Math.floor(c.expires) : 0;
      return [
        c.domain,
        includeSub,
        c.path || '/',
        c.secure ? 'TRUE' : 'FALSE',
        expiry,
        c.name,
        c.value,
      ].join('\t');
    }),
  ];

  await mkdir(path.dirname(output), { recursive: true });
  await writeFile(output, lines.join('\n') + '\n', { mode: 0o600 });
  console.log(`[douyin] exported ${cookies.length} cookie(s) to ${output}`);
} finally {
  await context.close();
}
